import { useEffect, useRef } from 'react';
import type { Entity, ResolvedState } from '../../scene/spec';
import { palette } from '../../scene/spec';
import { worldToScreen } from '../projection';
import { easing } from '../../scene/tween';
function entityPath(entity:Entity) {const [a,b]=entity.arc??[0,Math.PI/2];const radius=(entity.size?.[0]??1)*72;const start=[radius*Math.cos(a),radius*Math.sin(a)];const end=[radius*Math.cos(b),radius*Math.sin(b)];return `M 0 0 L ${start[0]} ${start[1]} A ${radius} ${radius} 0 ${b-a>Math.PI?1:0} 1 ${end[0]} ${end[1]} Z`;}
export default function SvgStage({state,selection,onSelect}: {state:ResolvedState;selection:string|null;onSelect:(id:string|null)=>void}) {
  const ref=useRef<SVGSVGElement>(null);
  useEffect(()=>{let frame=0;const start=performance.now();const nodes=Array.from(ref.current?.querySelectorAll<SVGElement>('[data-entity-id]')??[]);const previous=nodes.map(node=>{const matrix=node.getAttribute('transform')?.match(/translate\(([-\d.]+) ([-\d.]+)\)/);return {x:Number(matrix?.[1]??350),y:Number(matrix?.[2]??235)};});const animate=(time:number)=>{const t=easing(Math.min(1,(time-start)/400));nodes.forEach((node,i)=>{const e=state.entities[node.dataset.entityId!];if(!e)return;const p=worldToScreen(e.pos);node.setAttribute('transform',`translate(${previous[i].x+(p.x-previous[i].x)*t} ${previous[i].y+(p.y-previous[i].y)*t}) scale(${e.scale?.[0]??1} ${e.scale?.[2]??1})`);node.setAttribute('opacity',String(e.opacity??1));});if(t<1)frame=requestAnimationFrame(animate);};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame);},[state]);
  return <svg ref={ref} viewBox="0 0 700 440" aria-label="Interactive 2D workbench" role="group" style={{width:'100%',height:'100%',overflow:'visible'}}><defs><filter id="object-shadow"><feDropShadow dx="0" dy="6" stdDeviation="4" floodColor="#072D25" floodOpacity=".23"/></filter></defs>{Object.values(state.entities).sort((a,b)=>a.pos[1]-b.pos[1]).map(entity=>{const fill=palette[entity.color]??palette.whole;const p=worldToScreen(entity.pos);return <g key={entity.id} data-entity-id={entity.id} data-anchor-id={`entity-${entity.id}`} transform={`translate(${p.x} ${p.y})`} opacity={entity.opacity??1} filter="url(#object-shadow)" tabIndex={entity.kind==='label'?-1:0} role={entity.kind==='label'?undefined:'button'} aria-label={entity.text?.plain??`${entity.color} ${entity.kind}`} onPointerEnter={()=>onSelect(entity.tether??entity.id)} onPointerLeave={()=>onSelect(null)} onClick={()=>onSelect(entity.tether??entity.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(entity.tether??entity.id);}} style={{cursor:'pointer'}}>{entity.kind==='slice'?<path d={entityPath(entity)} fill={fill} stroke={selection===(entity.tether??entity.id)?'#FFE066':'#ffffff75'} strokeWidth={selection===(entity.tether??entity.id)?4:1.2}/>:entity.kind==='sphere'||entity.kind==='lantern'?<circle r={(entity.size?.[0]??.35)*72} fill={fill}/>:entity.kind==='label'||entity.kind==='token'?<text textAnchor="middle" fill={fill} fontFamily="Bricolage Grotesque" fontSize="23" fontWeight="600">{entity.text?.plain}</text>:<rect x={-(entity.size?.[0]??.6)*36} y={-(entity.size?.[2]??.6)*36} width={(entity.size?.[0]??.6)*72} height={(entity.size?.[2]??.6)*72} rx="5" fill={fill} stroke={selection===(entity.tether??entity.id)?'#FFE066':'#ffffff40'} strokeWidth={selection===(entity.tether??entity.id)?4:1}/>}</g>;})}</svg>;
}
